import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import {
  // WalletDisconnectButton,
  WalletMultiButton,
} from '@solana/wallet-adapter-react-ui'
import { useWallet } from '@solana/wallet-adapter-react'
import { useState, useEffect } from 'react'

import { getWalletTokenAddrs, getTokenMetadata } from './api/solana'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const { publicKey } = useWallet()
  const walletPublicKey = publicKey?.toString()
  const [wallet, setWallet] = useState(undefined as string | undefined)

  useEffect(() => {
    setWallet(walletPublicKey)
    if ( walletPublicKey ) {
      loadTokens( walletPublicKey )
    }
  }, [walletPublicKey])

  const loadTokens = async (address: string) => {
    const tokenAddresses = await getWalletTokenAddrs( address )
    console.log('found tokens ', tokenAddresses.length)
    for (let i=0;i<tokenAddresses.length;i++) {
      const metadata = await getTokenMetadata(tokenAddresses[i])

      if ( metadata &&
        metadata.data.updateAuthority === process.env.NEXT_PUBLIC_TOKEN_UPDATE_AUTHORITY &&
        metadata.data.data.symbol === process.env.NEXT_PUBLIC_TOKEN_SYMBOL
      ) {
        console.log('token matched ', metadata)
      }
    }
  }

  console.log('pubkey', walletPublicKey)

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          <WalletMultiButton />
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
